### ISSUE TITLE
network tests and pr runner

### ISSUE THREAD

**Issue by ozwaldorf** [fleek-network/ursa#74]
Network tests need updating as they are conflicting and immediately failing. Attempted running tests on current main as well as #70 

attempting to run tests with:
```sh
$ cargo test -r --all
```

gives:
- errors from SimpleLogger that the init has already been run
- commenting out the simple logger, we get errors from rocks db a lock is already established on the database

```
Finished release [optimized] target(s) in 0.25s
     Running unittests src/main.rs (target/release/deps/ursa-5979bd09da2b25a1)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/main.rs (target/release/deps/ursa_gateway-4a2da74aaf6d4012)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/lib.rs (target/release/deps/ursa_index_provider-f4def0148787e8db)

running 3 tests
test signed_head::tests::test_decode_signed_msg ... ok
test signed_head::tests::test_sign_head ... ok
test provider::tests::test_create_ad ... ok

test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 2.02s

     Running unittests src/lib.rs (target/release/deps/ursa_metrics-7057e3ef20b689e6)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/lib.rs (target/release/deps/ursa_network-d6c778180acd4664)

running 14 tests
test service::tests::get_block_local ... FAILED
test codec::protocol::tests::test_read_response ... FAILED
test codec::protocol::tests::test_write_request ... FAILED
test codec::protocol::tests::test_write_response ... FAILED
test codec::protocol::tests::test_read_request ... FAILED
test service::tests::add_block ... FAILED
test service::tests::test_bitswap_get ... FAILED
test service::tests::test_bitswap_sync ... FAILED
test service::tests::test_bitswap_get_block_not_found ... FAILED
test service::tests::test_network_mdns ... FAILED
test service::tests::test_network_gossip ... FAILED
test service::tests::test_network_discovery ... FAILED
test service::tests::test_network_req_res ... FAILED
test service::tests::test_network_start ... ok

failures:

---- service::tests::get_block_local stdout ----
thread 'service::tests::get_block_local' panicked at 'called `Result::unwrap()` on an `Err` value: SetLoggerError(())', crates/ursa-network/src/service.rs:494:14

---- codec::protocol::tests::test_read_response stdout ----
thread 'codec::protocol::tests::test_read_response' panicked at 'not yet implemented', crates/ursa-network/src/codec/protocol.rs:145:9

---- codec::protocol::tests::test_write_request stdout ----
thread 'codec::protocol::tests::test_write_request' panicked at 'not yet implemented', crates/ursa-network/src/codec/protocol.rs:150:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- codec::protocol::tests::test_write_response stdout ----
thread 'codec::protocol::tests::test_write_response' panicked at 'not yet implemented', crates/ursa-network/src/codec/protocol.rs:155:9

---- codec::protocol::tests::test_read_request stdout ----
thread 'codec::protocol::tests::test_read_request' panicked at 'not yet implemented', crates/ursa-network/src/codec/protocol.rs:140:9

---- service::tests::add_block stdout ----
thread 'service::tests::add_block' panicked at 'called `Result::unwrap()` on an `Err` value: SetLoggerError(())', crates/ursa-network/src/service.rs:494:14

---- service::tests::test_bitswap_get stdout ----
thread 'service::tests::test_bitswap_get' panicked at 'called `Result::unwrap()` on an `Err` value: SetLoggerError(())', crates/ursa-network/src/service.rs:494:14

---- service::tests::test_bitswap_sync stdout ----
thread 'service::tests::test_bitswap_sync' panicked at 'called `Result::unwrap()` on an `Err` value: SetLoggerError(())', crates/ursa-network/src/service.rs:494:14

---- service::tests::test_bitswap_get_block_not_found stdout ----
thread 'service::tests::test_bitswap_get_block_not_found' panicked at 'called `Result::unwrap()` on an `Err` value: SetLoggerError(())', crates/ursa-network/src/service.rs:494:14

---- service::tests::test_network_mdns stdout ----
thread 'service::tests::test_network_mdns' panicked at 'called `Result::unwrap()` on an `Err` value: SetLoggerError(())', crates/ursa-network/src/service.rs:494:14

---- service::tests::test_network_gossip stdout ----
thread 'service::tests::test_network_gossip' panicked at 'called `Result::unwrap()` on an `Err` value: SetLoggerError(())', crates/ursa-network/src/service.rs:494:14

---- service::tests::test_network_discovery stdout ----
thread 'service::tests::test_network_discovery' panicked at 'called `Result::unwrap()` on an `Err` value: SetLoggerError(())', crates/ursa-network/src/service.rs:494:14

---- service::tests::test_network_req_res stdout ----
thread 'service::tests::test_network_req_res' panicked at 'called `Result::unwrap()` on an `Err` value: SetLoggerError(())', crates/ursa-network/src/service.rs:494:14


failures:
    codec::protocol::tests::test_read_request
    codec::protocol::tests::test_read_response
    codec::protocol::tests::test_write_request
    codec::protocol::tests::test_write_response
    service::tests::add_block
    service::tests::get_block_local
    service::tests::test_bitswap_get
    service::tests::test_bitswap_get_block_not_found
    service::tests::test_bitswap_sync
    service::tests::test_network_discovery
    service::tests::test_network_gossip
    service::tests::test_network_mdns
    service::tests::test_network_req_res

test result: FAILED. 1 passed; 13 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.02s

error: test failed, to rerun pass `-p ursa-network --lib`
```

--- 

We should probably have the tests run automatically on every pull request to avoid failing tests on our main branch in the future. Alongside this, it would be nice to have a runner status badge on the readme document to show if the latest is successfully passing at a quick glance

**Comment by ozwaldorf** [comment]
ci tests added with #137 
network test fixed with #96
